// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvpdxDg22il-zyB_r0049V5gqWYDpU768',
    appId: '1:784461242413:web:cab7a121aa1c3d883598a4',
    messagingSenderId: '784461242413',
    projectId: 'bisonbytes-bot',
    authDomain: 'bisonbytes-bot.firebaseapp.com',
    storageBucket: 'bisonbytes-bot.appspot.com',
    measurementId: 'G-1N0Y8LRW6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6_bDBMFLKxW9pY0pq5bGLZeXiIJz9WSE',
    appId: '1:784461242413:android:b0cbf60f6cd42ccc3598a4',
    messagingSenderId: '784461242413',
    projectId: 'bisonbytes-bot',
    storageBucket: 'bisonbytes-bot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7YdsjfKicVlZrR5AJ2xEIuYRtp9tqJME',
    appId: '1:784461242413:ios:f279991b4f8c42483598a4',
    messagingSenderId: '784461242413',
    projectId: 'bisonbytes-bot',
    storageBucket: 'bisonbytes-bot.appspot.com',
    iosBundleId: 'com.example.bisonbytesBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7YdsjfKicVlZrR5AJ2xEIuYRtp9tqJME',
    appId: '1:784461242413:ios:2eb402b8904bb0773598a4',
    messagingSenderId: '784461242413',
    projectId: 'bisonbytes-bot',
    storageBucket: 'bisonbytes-bot.appspot.com',
    iosBundleId: 'com.example.bisonbytesBot.RunnerTests',
  );
}
